spring:
  cloud:
    nacos:
      discovery:
#        server-addr: 172.17.0.4:8848
        server-addr: nacos1:8848
  application:
    name: order-consumer
  main:
    allow-bean-definition-overriding: true
server:
  port: 9141
  servlet:
    context-path: /order
