spring:
  cloud:
    nacos:
      discovery:
#        server-addr: nacos1:8848
        server-addr: nacos1:8848
  application:
    name: auth-consumer
  main:
    allow-bean-definition-overriding: true
server:
  port: 9120
  servlet:
    context-path: /auth
