spring:
  cloud:
    nacos:
      discovery:
#        server-addr: 172.17.0.4:8848
        server-addr: localhost:8848
  application:
    name: commod-consumer
  main:
    allow-bean-definition-overriding: true
server:
  port: 9140
  servlet:
    context-path: /commod
