spring:
  cloud:
    nacos:
      discovery:
#        server-addr: 127.0.0.1:8845
        server-addr: 172.17.0.4:8848
  application:
    name: static
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 500MB
server:
  port: 9101


