spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8845
  application:
    name: static
  main:
    allow-bean-definition-overriding: true
server:
  port: 9701
  servlet:
    context-path: /static
