spring:
  cloud:
    nacos:
      discovery:
        server-addr: nacos1:8848
  application:
    name: market-consumer
  main:
    allow-bean-definition-overriding: true
server:
  port: 9160
  servlet:
    context-path: /market
